spring.application.name=IssueTracker

spring.datasource.url=jdbc:postgresql://localhost:5432/issuetracker

spring.datasource.username=postgres
spring.datasource.password=seilixx1514

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true
